name = "TapirSchedulersBenchmarks"
uuid = "7fec6468-e5d5-43bc-93c5-7a370b765647"
authors = ["Takafumi Arakaki <aka.tkf@gmail.com> and contributors"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
TapirSchedulers = "38de7e43-46ad-4ee9-b95c-91f351450dcb"

[compat]
julia = "1"
